export enum StoryActionTypes {
    ADD_STORY = "ADD_STORY",
    GET_STORIES = "GET_STORIES",
    ON_STORIES_ERROR = "ON_STORIES_ERROR",
    ON_STORIES_END = "ON_STORIES_END",
    SELECT_STORY = "SELECT_STORY"
}